language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexchevrier/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true alexchevrier/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-340410335482"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
